/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Retefuente;

import java.awt.Image;
import java.awt.Toolkit;

/**
 * Aplicación para realiza la liquidación de la retención en la fuente para asalariados segun lo establecido en el articulo 383 del ET.
 * @author Cristian Camilo Vargas González
 * @version 1.1
 */
public class Resultado extends javax.swing.JFrame {

    /**
     * Creates new form Ressultado
     */
    public Resultado() {
        initComponents();
        this.setLocationRelativeTo(null);//instrucción para que la interfaz aparezca en el centro
        
        Bienvenida datos = new Bienvenida(); //Creación de nuevo objeto para mostrar los datos ingresados en la clase "Bienvenida"
        //Datos obtenidos en la clase "Bienvenidos" mostrados en su respectivo jLabel
        jLabelNombre.setText(datos.nombre);
        jLabelCedula.setText(datos.cedula);
        
        IngresarDatos valores = new IngresarDatos();//Creación de nuevo objeto para mostrar los datos ingresados en la clase "IngresarDatos"
        //Datos obtenidos en la clase "IngresarDatos" mostrados en su respectivo jLabel
        jLabelSalario.setText(valores.salarioStr);
        jLabelOtrosIngresos.setText(valores.otrosIngresosStr);
        jLabelFondoSolidaridadPension.setText(valores.fondoSolidaridadPensionStr);
        jLabelIngresosBasicos.setText(valores.ingresosBasicosStr);
        jLabelEps.setText(valores.epsStr);
        jLabelPension.setText(valores.pensionStr);
        jLabelVoluntariosPension.setText(valores.voluntariosPensionStr);
        jLabelIngresosNoConstitutivos.setText(valores.ingresosNoConstitutivosStr);
        jLabelIngresosNetos.setText(valores.ingresosNetosStr);
        jLabelInteresesVivienda.setText(valores.interesesViviendaStr);
        jLabelPrepagada.setText(valores.prepagadaStr);
        jLabelDependientes.setText(valores.dependientesStr);
        jLabelDeducciones.setText(valores.deduccionStr);
        jLabelAfc.setText(valores.afcStr);
        jLabelRentaExenta25.setText(valores.rentaExenta25Str);
        jLabelExentas.setText(valores.exentaStr);
        jLabelBaseGravable.setText(valores.baseGravableStr);
        jLabelBaseReUvt.setText(valores.baseReUvtStr);
        jLabelRetencionUvt.setText(valores.retencionUvtStr);
        jLabelValorRetencion.setText(valores.valorRetencionStr);
        
        
        
    }
    //Declaración de función para escoger y establecer la imagen correspondiente al icono de la aplicación
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/calculadora.png"));
        return retValue;
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelOtrosIngresos = new javax.swing.JLabel();
        jLabelFondoSolidaridadPension = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabelIngresosBasicos = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelEps = new javax.swing.JLabel();
        jLabelPension = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelVoluntariosPension = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelIngresosNoConstitutivos = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabelIngresosNetos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelInteresesVivienda = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelPrepagada = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelDependientes = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabelDeducciones = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelAfc = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelRentaExenta25 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabelExentas = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabelBaseGravable = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelBaseReUvt = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabelRetencionUvt = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabelValorRetencion = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabelFondo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelFondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(720, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Resultado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 26));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNombre.setText("jLabel2");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 160, -1));

        jLabelCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCedula.setText("jLabel3");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 150, -1));

        jLabelSalario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSalario.setText("jLabel2");
        getContentPane().add(jLabelSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 150, -1));

        jLabelOtrosIngresos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOtrosIngresos.setText("jLabel2");
        getContentPane().add(jLabelOtrosIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 120, -1));

        jLabelFondoSolidaridadPension.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFondoSolidaridadPension.setText("jLabel2");
        getContentPane().add(jLabelFondoSolidaridadPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Salario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Otros Ingresos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cedula:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fondo de Solidaridad Pensional:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 290, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ingresos Brutos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabelIngresosBasicos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIngresosBasicos.setText("jLabel8");
        getContentPane().add(jLabelIngresosBasicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 640, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 290, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Aportes a EPS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Aportes a Pensión");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabelEps.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEps.setText("jLabel10");
        getContentPane().add(jLabelEps, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 110, -1));

        jLabelPension.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPension.setText("jLabel11");
        getContentPane().add(jLabelPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 110, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Aportes Voluntarios a Pension");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabelVoluntariosPension.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelVoluntariosPension.setText("jLabel11");
        getContentPane().add(jLabelVoluntariosPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total Ingresos No Constitutivos ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 290, 10));

        jLabelIngresosNoConstitutivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIngresosNoConstitutivos.setText("jLabel12");
        getContentPane().add(jLabelIngresosNoConstitutivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 110, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 290, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Total Ingresos Netos");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabelIngresosNetos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIngresosNetos.setText("jLabel13");
        getContentPane().add(jLabelIngresosNetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Intereses De Vivienda");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabelInteresesVivienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelInteresesVivienda.setText("jLabel14");
        getContentPane().add(jLabelInteresesVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Ingresos");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Deducciones");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Medicina Prepagada");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabelPrepagada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrepagada.setText("jLabel17");
        getContentPane().add(jLabelPrepagada, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Dependientes Economicos");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabelDependientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDependientes.setText("jLabel18");
        getContentPane().add(jLabelDependientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 90, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 10));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Total Deducciones");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jLabelDeducciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDeducciones.setText("jLabel19");
        getContentPane().add(jLabelDeducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Rentas Exentas");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Aportes a AFC");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabelAfc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAfc.setText("jLabel21");
        getContentPane().add(jLabelAfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 80, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Renta Exenta del 25%");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLabelRentaExenta25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRentaExenta25.setText("jLabel23");
        getContentPane().add(jLabelRentaExenta25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 80, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 290, 10));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Total Rentas Exentas");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabelExentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelExentas.setText("jLabel23");
        getContentPane().add(jLabelExentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 80, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Liquidación");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Base Gravable");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jLabelBaseGravable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBaseGravable.setText("jLabel25");
        getContentPane().add(jLabelBaseGravable, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 100, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Base Gravable en UVT");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        jLabelBaseReUvt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBaseReUvt.setText("jLabel26");
        getContentPane().add(jLabelBaseReUvt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Retención en UVT");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jLabelRetencionUvt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRetencionUvt.setText("jLabel27");
        getContentPane().add(jLabelRetencionUvt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 100, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Valor Retención");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        jLabelValorRetencion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorRetencion.setText("jLabel28");
        getContentPane().add(jLabelValorRetencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 70, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 290, 10));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));

        jLabelFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);//acción salir en el boton salir
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAfc;
    private javax.swing.JLabel jLabelBaseGravable;
    private javax.swing.JLabel jLabelBaseReUvt;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelDeducciones;
    private javax.swing.JLabel jLabelDependientes;
    private javax.swing.JLabel jLabelEps;
    private javax.swing.JLabel jLabelExentas;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondo2;
    private javax.swing.JLabel jLabelFondoSolidaridadPension;
    private javax.swing.JLabel jLabelIngresosBasicos;
    private javax.swing.JLabel jLabelIngresosNetos;
    private javax.swing.JLabel jLabelIngresosNoConstitutivos;
    private javax.swing.JLabel jLabelInteresesVivienda;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelOtrosIngresos;
    private javax.swing.JLabel jLabelPension;
    private javax.swing.JLabel jLabelPrepagada;
    private javax.swing.JLabel jLabelRentaExenta25;
    private javax.swing.JLabel jLabelRetencionUvt;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelValorRetencion;
    private javax.swing.JLabel jLabelVoluntariosPension;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
